python: "3.8"
build_dependencies:
  - pip
dependencies:
  - pandas>=1.0.3
  - virtualenv>=20.24.5,<21.0.0
  - wandb>=0.15.10,<0.16.0
  - scikit-learn>=1.3.1,<2.0.0
  - matplotlib>=3.7.2
  - pillow>=10.0.1,<11.0.0
  - plotly>=5.17.0
  - omegaconf>=2.3.0,<3.0.0
  - mlflow>=2.7.1,<3.0.0
