python: "3.8"
build_dependencies:
  - pip
dependencies:
  - mlflow>=2.7.1,<3.0.0
  - requests>=2.31.0,<3.0.0
  - hydra-core>=1.3.2,<2.0.0
  - wandb>=0.15.10,<0.16.0
  - virtualenv>=20.24.5,<21.0.0
  - hydra-joblib-launcher>=1.2.0
